services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: siva9666/expense-backend:node

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: siva9666/expense-frontend:node
  
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: siva9666/expense-mysql:node
