services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql:v1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: siva9666/expense-node-backend:v1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: siva9666/expense-node-frontend:v1
