services:
  mysql:
    image: mysql:v1
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
      - source: mysql
        target: /var/lib/mysql
        type: volume
    restart: on-failure
    networks:
      - expense

  backend:
    image: backend:v1
    container_name: backend
    environment:
      - DB_HOST=mysql
      - DB_USER=expense
      - DB_PWD=ExpenseApp@1
      - DB_DATABASE=transactions
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - expense

  frontend:
    image: frontend:v1
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: on-failure
    networks:
      - expense

networks:
  expense:
    driver: bridge

volumes:
  mysql:
