global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']
  - job_name: 'frontend-nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']